# Generated by Django 5.2.6 on 2025-09-23 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.courses')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.teacher')),
            ],
        ),
    ]
